# Generated by Django 3.2.9 on 2021-11-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='PredModel',
        ),
    ]
