# Generated by Django 4.0 on 2021-12-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_rename_model_predmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('path', models.CharField(choices=[], max_length=1)),
                ('for_stock', models.CharField(max_length=200, unique=True)),
                ('acc_50', models.DecimalField(decimal_places=2, max_digits=4)),
                ('acc_60', models.DecimalField(decimal_places=2, max_digits=4)),
                ('acc_70', models.DecimalField(decimal_places=2, max_digits=4)),
                ('acc_80', models.DecimalField(decimal_places=2, max_digits=4)),
                ('acc_90', models.DecimalField(decimal_places=2, max_digits=4)),
                ('acc_95', models.DecimalField(decimal_places=2, max_digits=4)),
                ('acc_99', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='PredModel',
        ),
    ]
