# Generated by Django 4.0 on 2021-12-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_predictionmodel_delete_predmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionmodel',
            name='path',
            field=models.CharField(blank=True, choices=[], max_length=1, null=True),
        ),
    ]
