# Generated by Django 4.0 on 2021-12-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_predictionmodel_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionmodel',
            name='path',
            field=models.CharField(choices=[], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='version',
            field=models.CharField(choices=[], default='1', max_length=1),
        ),
    ]
