# Generated by Django 4.0 on 2021-12-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_predictionmodel_for_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionmodel',
            name='num_nodes',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
