# Generated by Django 4.0 on 2021-12-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_predictionmodel_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionmodel',
            name='version',
            field=models.CharField(blank=True, choices=[], max_length=1000, null=True),
        ),
    ]
