# Generated by Django 4.0 on 2021-12-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_alter_predictionmodel_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionmodel',
            name='acc_50',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='acc_60',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='acc_70',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='acc_80',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='acc_90',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='acc_95',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='acc_99',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='num_nodes',
        ),
        migrations.RemoveField(
            model_name='predictionmodel',
            name='path',
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='for_stock',
            field=models.CharField(max_length=10),
        ),
    ]
