# Generated by Django 4.0 on 2021-12-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_predictionmodel_acc_50_predictionmodel_acc_60_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionmodel',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
