# Generated by Django 4.0 on 2021-12-25 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_alter_predictionmodel_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionmodel',
            name='version',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
