# Generated by Django 4.0 on 2021-12-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_alter_predictionmodel_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionmodel',
            name='acc_50',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='acc_60',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='acc_70',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='acc_80',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='acc_90',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='acc_95',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='acc_99',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='predictionmodel',
            name='num_nodes',
            field=models.IntegerField(null=True),
        ),
    ]
